### ISSUE TITLE
Regex matches any URL containing "github" in its path

### ISSUE THREAD

**Issue by sangster** [DarkThemeHub/GithubDarkTheme#153]
**Describe the bug**

The regular expression used to match pages is too permissive. It will match any URL containing `github`, even if it's just in the path part of the URL.

Examples:
 - https://serokell.io/blog/comparison-of-github-and-gitlab
 - https://www.howtogeek.com/180167/htg-explains-what-is-github-and-what-do-geeks-use-it-for/

Affected Regexp:

```regex
^https?://(?!www.google.com)(((?!desktop).*.)?(githubusercontent|githubstatus|github).(?!io|myshopify|blog)).*
```

**Expected behavior**

I expect this theme to only apply on `github.com` (and perhaps related domains?).

**Screenshot**

![screen](https://user-images.githubusercontent.com/996850/81033532-de80e480-8e48-11ea-80c6-fefbf2a691fb.png)

**Comment by sangster** [comment]
I noticed in #136 that you posted a link to this regex test page: https://regex101.com/r/bW6cYw/3

I imagine this regex is from a previous version, as it's not the regex used in the current version. See this page, which includes the example URLs from above: https://regex101.com/r/sEZPE5/2

**Comment by Snazzie** [comment]
This was actually fixed in #152 :)
https://regex101.com/r/sEZPE5/3

**Comment by Snazzie** [comment]
Make sure you havent edited the style (which prevents it from auto updating).

Currently, the latest version is 1.27.0

**Comment by Snazzie** [comment]
https://github.com/DarkThemeHub/GithubDarkTheme/blob/24e799fb46edafc347668715835c75c5ea506944/UrlRegex.txt#L1

The regex you pasted isnt up to date.

**Comment by sangster** [comment]
I installed it from this page: https://userstyles.org/styles/168350/githubdarktheme

Strangely, I still get this problem if I delete the style outright, and re-add it (from the above link). Perhaps there's something wrong with my Firefox profile.

**Comment by sangster** [comment]
Here's the regex, verbatim: 
```regex
^https?://(?!www.google.com)(((?!desktop).*.)?(githubusercontent|githubstatus|github).(?!io|myshopify|blog)).*
```

**Comment by Snazzie** [comment]
Try removing the style and installing via https://github.com/DarkThemeHub/GithubDarkTheme#step-2 

Userstyles hasnt been reliable with updating the style file

**Comment by sangster** [comment]
Boom. That did it. 

Thanks bunches for your time. Sorry for not reading the README. It never even crossed my mind that userstyles.org could be the issue.

cheers!

**Comment by Snazzie** [comment]
No problem! If you've come across any other bugs, dont hesitate to submit an issue :)

**Comment by Snazzie** [comment]
I just did a sanity check on the style in userstyles site. it has the correct regex.  what the heck...

I noticed the style file when installed is different to what i put in. I guess they process it and the regex processor is whack...

I would take this theme off there, but its my only source of users. 😞
